[extract-db]
exec = [
  "python",
  "-m",
  "app.cmd",
  "backupdb",
  "--compress",
  "--flat",
  "{{ env.EXTRACT_DIR }}",
]
if = "env.EXTRACT_DIR"
schedule = "@midnight"

[extract-ndt]
shell = '''
  # move NDT data files into place
  find "$DATA_DIR" -type f \! -empty -print0 | xargs -0 -r mv -t "$EXTRACT_DIR"

  # clean up empty source directories
  find "$DATA_DIR" -mindepth 1 -type d -empty -delete
'''
if = "env.EXTRACT_DIR and env.DATA_DIR"
schedule = "@midnight"
